In [1]:
import numpy as np

## Dataset from sjtu

In [2]:
## XMEGA data from sjtu includes 6 devices, 
## for each device, they have train data, attack data (either for testing or tuning), 
## also includes corresponding labels and plaintexts for train and attack data
## print info of data in device02 of sjtu

attack_d2 = np.load('./Data/device02/X_attack.npy')
attack_label_d2 = np.load('./Data/device02/Y_attack.npy')
train_d2 = np.load('./Data/device02/X_train.npy')
train_label_d2 = np.load('./Data/device02/Y_train.npy')
train_plaintext = np.load('./Data/device02/plaintexts_train.npy')

print('--------> Dataset information from SJTU <--------')
print(f"attributes of dataset in one device includes:{'Train:trace-label-plaintext','Attack:trace-label-plaintext'}")
print(f"shape of attack data in device02 is {attack_d2.shape}")
print(f"shape of attack labels in device02 is {attack_label_d2.shape}")
print(f"shape of train data in device02 is {train_d2.shape}")
print(f"shape of train labels in device02 is {train_label_d2.shape}, class includes {set(train_label_d2)}")
print(f"shape of train plaintext in device02 is {train_plaintext.shape}")


print('\n')
print(f"Sample of train data: {train_d2}")
print(f"Sample of train label:  {train_label_d2} ")
print(f"Sample of train plaintext: {train_plaintext}, max number of plaintext: {max(train_plaintext)}")

--------> Dataset information from SJTU <--------
attributes of dataset in one device includes:('Train:trace-label-plaintext', 'Attack:trace-label-plaintext')
shape of attack data in device02 is (5000, 500)
shape of attack labels in device02 is (5000,)
shape of train data in device02 is (25000, 500)
shape of train labels in device02 is (25000,), class includes {0, 1, 2, 3, 4, 5, 6, 7, 8}
shape of train plaintext in device02 is (25000,)


Sample of train data: [[-1449.  -289. -1739. ... -1449. -2319. -1449.]
 [  289.     0.     0. ...  1739. -3189. -1449.]
 [  579. -1159.     0. ...   579. -3478. -1449.]
 ...
 [ 3768. -1449.   289. ...  2029. -2899. -1449.]
 [ 2609. -1159.   869. ...  2319. -2319. -1739.]
 [    0.   289.  -289. ...  2609. -2609. -1159.]]
Sample of train label:  [7 2 5 ... 3 3 3] 
Sample of train plaintext: [ 36 236  41 ... 116 198 243], max number of plaintext: 255


## Our Dataset 

In [5]:
## Our XMEGA unmasked data includes two devices here,
## print info of data in device02  of ours

attack_d2 = np.load('./our_data/unmasked/device02/PC2_CB2_TDX3_K3_U_20k_0317.npz')
tuning_d2 = np.load('./our_data/unmasked/device02/PC2_CB2_TDX3_K3_U_2500_b_0317.npz')
attack_label_d2 = np.load('./our_data/device02/Y_attack.npy')

print('--------> Dataset information of Ours <--------')
print(f"attributes of attack dataset in device02 includes:{attack_d2.files}")
print(f"attributes of tuning dataset in device02 includes:{tuning_d2.files}")
print(f"shape of attack data trace in device02 is {attack_d2['power_trace'].shape}")
print(f"shape of tuning data trace in device02 is {tuning_d2['power_trace'].shape}")
print(f"shape of attack plaintext in device02 is {attack_d2['plain_text'].shape}")
print(f"shape of tuning plaintext in device02 is {tuning_d2['plain_text'].shape}")
print(f"shape of attack data key in device02 is {attack_d2['key'].shape}")
print(f"shape of attack label in device02 is {attack_label_d2.shape}, num of class: {max(attack_label_d2)+1}")


print('\n')
print(f"Sample of attack data: {attack_d2['power_trace']}")
print(f"Sample of attack key:  {attack_d2['key']} ")
print(f"Sample of attack plaintext: {attack_d2['plain_text']}")
print(f"Sample of attack label: {attack_label_d2}")

--------> Dataset information of Ours <--------
attributes of attack dataset in device02 includes:['power_trace', 'plain_text', 'key']
attributes of tuning dataset in device02 includes:['power_trace', 'plain_text']
shape of attack data trace in device02 is (20000, 5000)
shape of tuning data trace in device02 is (2500, 5000)
shape of attack plaintext in device02 is (20000, 16)
shape of tuning plaintext in device02 is (2500, 16)
shape of attack data key in device02 is (16,)
shape of attack label in device02 is (20000,), num of class: 256


Sample of attack data: [[ 0.05566406 -0.31445312 -0.16796875 ... -0.09960938  0.0078125
  -0.01074219]
 [ 0.06054688 -0.31738281 -0.171875   ... -0.10058594  0.00585938
  -0.00683594]
 [ 0.046875   -0.33203125 -0.18359375 ... -0.10742188  0.00195312
  -0.01074219]
 ...
 [ 0.0625     -0.31347656 -0.16699219 ... -0.09472656  0.00976562
   0.        ]
 [ 0.06640625 -0.3125     -0.16992188 ... -0.11328125 -0.00585938
  -0.01953125]
 [ 0.0625     -0.3115234

## Our Dataset after Pre-processing

In [4]:
## pre-processe our dataset, to make the format consistent with dataset of SJTU
## print info of data in device01  of ours

train_d2 = np.load('./our_data/device01/X_train.npy')
train_label_d2 = np.load('./our_data/device01/Y_train.npy')
train_plaintext = np.load('./our_data/device01/plaintexts_train.npy')

print('--------> Dataset information of Preprocessed data of Ours <--------')
print(f"attributes of dataset in one device includes:{'Train:trace-label-plaintext','Attack:trace-label-plaintext'}")
print(f"shape of train data trace in device01 is {train_d2.shape}")
print(f"shape of train plaintext in device01 is {train_plaintext.shape}")
print(f"shape of train label in device01 is {train_label_d2.shape}, num of class: {max(train_label_d2)+1}")


print('\n')
print(f"Sample of train data: {train_d2}")
print(f"Sample of train plaintext: {train_plaintext}")
print(f"Sample of train label: {train_label_d2}")

--------> Dataset information of Preprocessed data of Ours <--------
attributes of dataset in one device includes:('Train:trace-label-plaintext', 'Attack:trace-label-plaintext')
shape of train data trace in device01 is (200000, 1000)
shape of train plaintext in device01 is (200000,)
shape of train label in device01 is (200000,), num of class: 256


Sample of train data: [[ 0.15722656  0.02050781  0.1484375  ... -0.24804688 -0.09667969
  -0.05664062]
 [ 0.1484375   0.01367188  0.14355469 ... -0.296875   -0.14550781
  -0.09277344]
 [ 0.14453125  0.00390625  0.1328125  ... -0.22070312 -0.07714844
  -0.04296875]
 ...
 [ 0.14941406  0.01660156  0.14453125 ... -0.18554688 -0.04785156
  -0.01660156]
 [ 0.14648438  0.01074219  0.13964844 ... -0.20996094 -0.0703125
  -0.03417969]
 [ 0.15429688  0.00976562  0.13769531 ... -0.2265625  -0.08789062
  -0.05566406]]
Sample of train plaintext: [158 187 104 ...  39 209 215]
Sample of train label: [213  96  26 ... 254  45 176]
